# Generated by Django 4.0.7 on 2022-09-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cart_customer_alter_config_country_and_more'),
        ('giftcertificate', '0003_auto_20150922_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcertificate',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='giftcertificateusage',
            name='orderpayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.orderpayment', verbose_name='Order Payment'),
        ),
    ]
