# Generated by Django 4.0.7 on 2022-09-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l10n', '0001_initial'),
        ('contact', '0003_auto_20180829_1601'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='config',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='l10n.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('In Person', 'In Person'), ('Show', 'Show')], max_length=50, verbose_name='Order method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Temp', 'Temp'), ('New', 'New'), ('Blocked', 'Blocked'), ('In Process', 'In Process'), ('Billed', 'Billed'), ('Shipped', 'Shipped'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], help_text='This is set automatically.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderitemdetail',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='orderpaymentfailure',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentfailures', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Temp', 'Temp'), ('New', 'New'), ('Blocked', 'Blocked'), ('In Process', 'In Process'), ('Billed', 'Billed'), ('Shipped', 'Shipped'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], max_length=20, verbose_name='Status'),
        ),
    ]
